import llms from "@/lib/data/llms.json";

// Text for /llms.txt and /llms-full.txt. Generated by
// _legacy-static-site/scripts/llms.py via `npm run content:export`, the same
// builder that writes the static site's copies, so both sites serve one text.

export const LLMS_TXT: string = llms.llms;
export const LLMS_FULL_TXT: string = llms.llmsFull;

/** Plain-text response; `noindex` keeps the raw file out of web search results
 *  without stopping AI crawlers from fetching it. */
export function llmsResponse(body: string): Response {
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "X-Robots-Tag": "noindex",
    },
  });
}
