import {
  Award,
  BadgeCheck,
  BarChart3,
  Boxes,
  Briefcase,
  Cctv,
  CalendarCheck,
  Cloud,
  CloudCog,
  Code2,
  Cpu,
  Database,
  DatabaseBackup,
  Factory,
  FileLock2,
  Globe,
  HardDrive,
  KeyRound,
  Layers,
  LifeBuoy,
  Lightbulb,
  LockKeyhole,
  Mail,
  MonitorCog,
  Network,
  PieChart,
  Plug,
  Radar,
  Receipt,
  RefreshCcw,
  Router,
  ScanSearch,
  Server,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Siren,
  Workflow,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

// Icons for the service categories (lib/services.ts), their sub-services and
// the software products (lib/products.ts). Client-safe: no server imports.

export const categoryIcons: Record<string, LucideIcon> = {
  danismanlik: Lightbulb,
  "siber-guvenlik": ShieldCheck,
  "sistem-network": Network,
  "bulut-yedekleme": Cloud,
  "yazilim-dijital": Code2,
  lisanslama: KeyRound,
};

const serviceIconMap: Record<string, LucideIcon> = {
  "iso-27001-bilgi-guvenligi-danismanligi": Award,
  "kvkk-danismanligi": FileLock2,
  "it-danismanlik-hizmetleri": MonitorCog,
  "logo-erp-destek-ve-danismanlik": Briefcase,
  "yazilim-ve-dijital-donusum-danismanligi": Workflow,
  "siber-guvenlik-danismanligi": ShieldCheck,
  "sizma-testi-penetrasyon-testi": Radar,
  "guvenlik-acigi-ve-zafiyet-analizi": ScanSearch,
  "firewall-ve-ag-guvenligi": ShieldAlert,
  "edr-antivirus-cozumleri": Cpu,
  "dlp-veri-kaybi-onleme-cozumleri": LockKeyhole,
  "siem-ve-log-yonetimi": Siren,
  "iso-27001-teknik-guvenlik-cozumleri": BadgeCheck,
  "sistem-ve-network-danismanligi": Network,
  "ag-altyapisi-kurulum-ve-yonetimi": Router,
  "sunucu-kurulum-ve-yonetimi": Server,
  "veri-merkezi-cozumleri": ServerCog,
  "sanallastirma-cozumleri": Layers,
  "wifi-ve-kablosuz-ag-cozumleri": Wifi,
  "ip-kamera-guvenlik-kamerasi-sistemleri": Cctv,
  "firewall-ve-vpn-cozumleri": ShieldAlert,
  "sistem-entegrasyonu": Shuffle,
  "it-bakim-ve-destek-hizmetleri": Wrench,
  "bulut-cozumleri": Cloud,
  "microsoft-365-cozumleri": Mail,
  "microsoft-azure-cozumleri": CloudCog,
  "aws-bulut-cozumleri": CloudCog,
  "veri-yedekleme-cozumleri": DatabaseBackup,
  "felaket-kurtarma-disaster-recovery": RefreshCcw,
  "is-surekliligi-cozumleri": LifeBuoy,
  "veri-kurtarma-hizmetleri": HardDrive,
  "ozel-yazilim-gelistirme": Code2,
  "web-uygulama-gelistirme": Globe,
  "web-tasarim-ve-kurumsal-web-sitesi": Globe,
  "api-ve-sistem-entegrasyonlari": Plug,
  "erp-entegrasyonlari": Database,
  "is-sureci-otomasyonlari": Workflow,
  "raporlama-ve-dashboard-cozumleri": BarChart3,
};

export function serviceIcon(key: string): LucideIcon {
  return serviceIconMap[key] ?? KeyRound;
}

export const productIcons: Record<string, LucideIcon> = {
  atlas: PieChart,
  "cek-senet-programi": Receipt,
  cyberware: ShieldCheck,
  cyberquan: Factory,
  cyberhost: Wifi,
  pentforce: Radar,
  "fornet-enterprise": Network,
  otium: CalendarCheck,
  orbit: Boxes,
};
